name: Feature Request
description: Suggest an idea for the project.
labels:
  - feature request
body:
  - type: textarea
    id: what-cant-you-do
    attributes:
      label: What can't you do?
      description: Describe in detail what you're unable to currently do
      placeholder: I'm unable to...
    validations:
      required: true
  - type: textarea
    id: how-work
    attributes:
      label: How would you like it to work?
      description: Describe in detail how the feature should work
      placeholder: I want it to work by...
    validations:
      required: true
  - type: textarea
    id: extra-context
    attributes:
      label: Additional context
      description: Any extra deails on the feature you're requesting